# Generated by Django 2.0.13 on 2023-02-18 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='xname',
        ),
    ]
